baseurl = "http://tiago.dalligna.com/"
languageCode = "en-us"
title = "Tiago on tech"
theme = "purehugo"
Paginate = 10
disqusShortname = "tiagodll"

[params]
  # twitterName = "tiagodll"
  githubName = "tiagodll"
  stackOverflowId = "392974"
  linkedinName = "tiagodll"
  description = "My random thoughts and experiences"
  dateFormat = "2021-07-22"

[permalinks]
  posts = "/:year/:month/:title/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
