name: Deploy to server

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0 
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        
    - name: Build
      run: hugo --minify
      
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        private_key: ${{ secrets.SERVER_SSH_KEY }}
        scp_source: ./public
        scp_target: /var/www/blog
